ALTER TABLE blogs ADD COLUMN slug VARCHAR(255) UNIQUE AFTER title;
ALTER TABLE products ADD COLUMN slug VARCHAR(255) UNIQUE AFTER category_id;
ALTER TABLE categories ADD COLUMN slug VARCHAR(255) UNIQUE AFTER name;
ALTER TABLE promos ADD COLUMN slug VARCHAR(255) UNIQUE AFTER title;
ALTER TABLE branches ADD COLUMN slug VARCHAR(255) UNIQUE AFTER name;
