CREATE TABLE IF NOT EXISTS `branches` (
  `id` INT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID=1 digunakan sebagai HQ',
  `name` VARCHAR(100) NOT NULL,
  `address` TEXT,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);